---
- name: Playbook Name
  hosts: rhelvm-5
  gather_facts: false
  become: true

  vars:
    some_var: 'test variable'

  tasks:
    - name: 'Precheck | Get the precheck facts'
      ansible.builtin.setup:
      register: precheck_facts_result

    - name: debug precheck_facts_result
      ansible.builtin.debug:
        var: precheck_facts_result

