---
- name: "Linux Patching : Precheck Process"
  hosts: "{{ vm_nodes }}"
  strategy: free
  gather_facts: false
  become: true
  tasks:
    - name: 'Include pre-check role'
      ansible.builtin.include_role: 
        name: precheck_linux