- name: "Linux Patching : Check reboot"
  hosts: "{{ vm_nodes }}"
  gather_facts: false
  become: true
  vars:
    reboot_timeout: 600
    check_conn_freq: 5
    post_reboot_delay: 30
    test_command: whoami
  tasks:

    - name: 'SANITY_REBOOT | Perform Sanity Reboot'
      ansible.builtin.reboot:
        reboot_timeout: "{{ reboot_timeout }}"
        connect_timeout: "{{ check_conn_freq }}"
        post_reboot_delay: "{{ post_reboot_delay }}"
        test_command: "{{ test_command }}"


    # - name: 'Show all stats data var'
    #   ansible.builtin.debug: 
    #     var: pre_check[inventory_hostname_short]
    # - name: 'Run only if pre_check_fail is not true'
    #   ansible.builtin.debug: 
    #     msg: 'All good in precheck for {{ inventory_hostname_short }}'
    #   when: not pre_check[inventory_hostname_short].pre_check_fail