---
- name: Workflow Test PB2
  hosts: "{{ vm_nodes }}"
  gather_facts: true
  become: false

  vars:
    some_var: 'test variable'

  tasks:
    
    # - name: 'PB2: Fail if rhelvm3'
    #   ansible.builtin.fail:
    #     msg: "Failing RHELVM3"
    #   when: inventory_hostname == 'rhelvm-3'

    - name: 'debug hosts'
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} works"
      