---
- name: Remediate Wildfly Compliance Issues
  hosts: "{{ target_wildfly_servers }}"
  become: yes
  gather_facts: true
  vars:
    jboss_home: /opt/jboss/wildfly
    java_home: /usr/lib/jvm/java
    jdk_id: openjdk
    java_version: '11.0.12'
  environment:
    JAVA_HOME: "{{ java_home }}"

  roles:
    - wildfly_add_on_checks_remediation
