---
# tasks file for precheck_linux
# - name: 'Precheck | Check Connectivity'
#   ansible.builtin.include_tasks:
#     file: 'check_connectivity.yml'
- name: 'Precheck | Set default facts'
  ansible.builtin.set_fact:
    pre_check_status: true
    pre_check_fail: false
    pre_check_fail_stage: ''
    pre_check_fail_msg: '' 

- name: 'Precheck | Gather all facts'
  ansible.builtin.include_tasks:
    file: 'gather_all_facts.yml'
  when: not pre_check_fail

# Do the FS/VG Space Check
- name: 'Precheck | Check FS/VG Free Space'
  ansible.builtin.include_tasks:
    file: 'fs_vg_freespace_check.yml'
  when: not pre_check_fail

# Do the lvm Snapshots
- name: 'Precheck | Create LVM Snapshots'
  ansible.builtin.include_tasks:
    file: 'create_lvm_snapshots.yml'
  when: not pre_check_fail

# Run the Pre-Check Script
- name: 'Precheck | Run precheck script'
  ansible.builtin.include_tasks:
    file: 'run_pre_check_script.yml'
  when: not pre_check_fail

# Run the Pre-Check Script
- name: 'Precheck | Capture all precheck details'
  ansible.builtin.include_tasks:
    file: 'capture_precheck_results.yml'
  #when: not pre_check_fail