---
- name: Update Packages
  hosts: "{{ vm_update_group }}"
  become: yes
  gather_facts: yes
  tasks:

    - name: Update Packages
      yum:
        name: "{{ required_packages }}"
        state: latest
        exclude: "{{ exclude_pkgs }}"
      when: inventory_hostname in snapshot_ok_vms

    - name: Print Skipped VMs due to snapshot failure
      debug:
        msg: "Snapshot failed for {{ inventory_hostname }} hence it is not updated"
      when: inventory_hostname not in snapshot_ok_vms
