---
- name: Update Packages
  hosts: "{{ vm_name }}"
  become: yes
  gather_facts: yes
  tasks:
    - name: Update Packages
      yum:
        name: "{{ required_packages }}"
        state: latest
        exclude: "{{ exclude_pkgs }}"
     
