---
- name: Update Packages
  hosts: "{{ vm_update_group }}"
  become: yes
  gather_facts: yes
  tasks:
    - debug:
        var: snapshot_ok_vms

    - name: Update Packages
      yum:
        name: "{{ required_packages }}"
        state: latest
        exclude: "{{ exclude_pkgs }}"
      when: inventory_hostname in snapshot_ok_vms
     
