galaxy_info:
  description: Apply Linux OS patches

  min_ansible_version: "2.1"

  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - "8"
        - "9"