---
- name: Get ServiceNow Incident Data
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Retrieve Incident Information
      servicenow.itsm.incident_info:
        instance: "https://your_instance.service-now.com"  # Your ServiceNow URL
        username: "your_username"
        password: "your_password"
        query: "number=INC0010023"  # Example incident number. Replace or use another query 
      register: incident_result

    - debug:
        var: incident_result