---
- name: Get ServiceNow Incident Data
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Retrieve Incident Information
      servicenow.itsm.incident_info:
        instance: "https://tmgsnowdev.service-now.com/"  # Your ServiceNow URL
        username: "admin"
        password: "P@ssw0rd"
        query: "number=INC0269932"  # Example incident number. Replace or use another query 
      register: incident_result

    - debug:
        var: incident_result