---
- name: Test ServiceNow Endpoint Connection
  hosts: localhost  # Run this locally for simplicity
  gather_facts: false

  vars:
    servicenow_instance: "https://your_instance.service-now.com"  # Your ServiceNow URL
    servicenow_user: "your_username"                                # ServiceNow username
    servicenow_password: "your_password"                            # ServiceNow password (be secure!)
    
  tasks:
    # Ping the ServiceNow instance with basic auth (if applicable)
    - name: Check ServiceNow Endpoint Availability
      uri:
        url: "{{ servicenow_instance }}/api/now/table/incident?sysparm_limit=1"
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        method: GET
        status_code: 200
        validate_certs: false  # Set to true if your instance has a valid SSL cert
      register: http_result
      ignore_errors: true  # Allow other tasks to run even if this fails
      
    - name: Display ServiceNow Endpoint Results
      debug:
        msg: "{{ http_result }}"

    # Additional Check: Query a table (more rigorous but requires permissions)
    - name: Query a Sample Table (Optional)
      servicenow_table:
        instance: "{{ servicenow_instance }}"
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        table: "incident"
        query: "active=true"
        state: list
      register: table_result
      ignore_errors: true
      
    - name: Display Table Query Results
      debug:
        msg: "{{ table_result }}"

    # Handle Potential Failures
    - name: Fail if Connection is Not Available
      fail:
        msg: "ServiceNow endpoint connection test failed!"
      when: http_result is failed or (table_result is defined and table_result is failed)