---
- name: Reset User Password Based on ServiceNow Ticket
  hosts: localhost
  gather_facts: false

  vars:
    servicenow_instance: "https://your_instance.service-now.com"
    servicenow_user: "your_username"
    servicenow_password: "your_password"
    ticket_number: "INC0010023"  # Example ticket number, replace with variable input
    ad_server: "your_ad_server"  
    ad_user: "your_ad_user"
    ad_password: "your_ad_password"

  tasks:
    - name: Get Username from ServiceNow Ticket
      servicenow.itsm.incident_info:
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        query: "number={{ ticket_number }}"
      register: incident_result

    - name: Extract Username
      set_fact:
        requested_username: "{{ incident_result.query_results[0].caller_id.value }}"  
      when: incident_result.query_results is defined and incident_result.query_results | length > 0 

    - name: Reset Password in Active Directory
      win_domain_user:
        name: "{{ requested_username }}"
        password: "NewStrongPassword123!" 
        state: present
        domain_server: "{{ ad_server }}"
        domain_username: "{{ ad_user }}"
        domain_password: "{{ ad_password }}"
      when: requested_username is defined 