---
- name: ServiceNow Connection Test
  hosts: localhost
  gather_facts: false
  
  vars:
    servicenow_instance: "https://tmgsnowdev.service-now.com/"  # Your ServiceNow URL
    servicenow_user: "admin"                                # ServiceNow username
    servicenow_password: "P@ssw0rd"                            # ServiceNow password (be secure!)

  tasks:
    # Test Authentication
    - name: Test Connection to ServiceNow
      servicenow.itsm.incident:  
        state: list
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        query: "sysparm_limit=1"  # Fetch only one record to keep it lightweight
      register: result
      ignore_errors: true  # Allow other tasks to run even if this fails

    - name: Display Connection Result
      debug:
        msg: "{{ result }}"

    - name: Fail if Connection is Not Available
      fail:
        msg: "ServiceNow connection test failed!"
      when: result is failed  # Fail the playbook if the connection fails