---
- name: "OS Patching : Precheck Process"
  hosts: "{{ app_servers }}"
  #strategy: free
  gather_facts: false
  become: true
  tasks:
    - name: 'Include OS pre-check role'
      ansible.builtin.include_role: 
        name: 'precheck_{{ app_server_os_type }}'

    - name: 'debug facts'
      ansible.builtin.debug: 
        var: pre_check_fail | default(false)

    - name: 'Test Failure'
      ansible.builtin.set_fact: 
        pre_check_fail: true
      when: inventory_hostname == 'rhelvm-5'

    - name: 'OS_PRE_CHECK | Fail if there were errors in the pre-checks'
      ansible.builtin.fail: 
        msg: 'OS_PRE_CHECK for {{ inventory_hostname }} has failed. Failed stage: {{ pre_check_fail_stage }}'     
      when: pre_check_fail

    # - name: 'debug facts'
    #   ansible.builtin.debug: 
    #     msg: fact_pre_check 
