---
- name: "OS Patching : Precheck Process"
  hosts: "{{ db_servers }}"
  #strategy: free
  gather_facts: false
  become: true
  tasks:
    - name: 'BLOCK : Check if the os type is supported'
      block:
        - name: 'Include capture pre-check results role'
          ansible.builtin.include_role: 
            name: 'capture_results'
          vars:
            result_out_dir: '{{ interim_results_dir }}'
            result_out_filename: '{{ jira_key }}-db-pre_check'
            result_data_var: 'pre_check'
            result_data: "{{ pre_check }}"
      
      when:  
        - db_server_os_type in supported_nix_os_types 
        - not (run_only_post_check | bool)


 