---
- name: "OS Patching : Precheck Process"
  hosts: "{{ app_servers }}"
  #strategy: free
  gather_facts: false
  become: true
  tasks:
    - name: 'Include OS pre-check role'
      ansible.builtin.include_role: 
        name: 'precheck_{{ app_server_os_type }}'

    - name: 'debug facts'
      ansible.builtin.debug: 
        var: pre_check_fail | default(false)
      #run_once: true

    # - name: 'debug facts'
    #   ansible.builtin.debug: 
    #     msg: fact_pre_check 
