---
- name: "App Shutdown | Run App Shutdown scripts"
  hosts: "{{ app_servers }}"
  #strategy: free
  gather_facts: false
  become: true
  tasks:
    - name: 'BLOCK : Check if the os type is supported'
      block:
        - name: 'App Shutdown | Run App Shutdown scripts'
          ansible.builtin.include_role: 
            name: 'run_shell_scripts'
          vars:
            v_shell_scripts: "{{ app_stop_scripts }}"
            v_stage: 'APP_SHUTDOWN'
            v_script_user: "{{ app_scripts_user }}"
      
      when:  
        - app_server_os_type in supported_nix_os_types 
        - not (run_only_post_check | bool)
      
