---
- name: "App Startup | Run App Startup scripts"
  hosts: "{{ app_servers }}"
  #strategy: free
  gather_facts: false
  become: true
  tasks:
    - name: 'BLOCK : Check if the os type is supported'
      block:
        - name: 'App Startup | Run App Startup scripts'
          ansible.builtin.include_role: 
            name: 'run_shell_scripts'
          vars:
            v_shell_scripts: "{{ app_start_scripts }}"
            v_stage: 'APP_STARTUP'
            v_script_user: "{{ app_scripts_user }}"
      
      when: app_server_os_type in supported_nix_os_types 

      
