- name: 'Patch |  BLOCK : Perform Patching'
  block:

    - name: 'OS_UPDATE | Perform patching'
      ansible.builtin.debug:
        msg: 'Solaris Patching not yet implemented. Skipping !!'

    - name: 'OS_UPDATE | Perform patching'
      ansible.builtin.shell:
        cmd: "pkg update --accept '{{ required_pkgs }}'"
        #chdir: "{{ v_script | dirname }}"
      become: true
      async: "{{ patching_timeout }}"
      poll: "{{ patching_poll }}"
      register: pkg_update_result   

    - name: 'OS_UPDATE | Debug pkg update output'
      ansible.builtin.debug:
        var: pkg_update_result.stdout_lines + pkg_update_result.stderr_lines


    # - name: 'OS_UPDATE | Perform patching'
    #   ansible.builtin.yum:
    #     name: "{{ required_pkgs }}"
    #     state: latest
    #     exclude: "{{ exclude_pkgs }}"
    #   async: "{{ patching_timeout }}"
    #   poll: "{{ patching_poll }}"
    #   register: yum_update_result

  rescue:
    - name: 'OS_UPDATE |  Set failure message'
      ansible.builtin.set_fact:
        patch_fail: true
        patch_fail_stage: 'OS_UPDATE'
        patch_fail_msg: "{{ ansible_failed_result }}"     