---
- name: Retrieve VMware ESXi Host Inventory
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware

  tasks:
    - name: Get ESXi Host Information
      community.vmware.vmware_host_inventory:
        hostname: "192.168.50.26"
        username: "root"
        password: "Afk5min$!@#"
        validate_certs: no
        schema: "summary" # This will fetch the summary of the host. You can change it based on your requirements.
      delegate_to: localhost
      register: esxi_host_info

    - name: Display ESXi Host Information
      debug:
        var: esxi_host_info
    - name: Display VM List
      debug:
        var: vm_list.virtual_machines