---
- name: Playbook using a collection
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware
- name: Retrieve VMware ESX Inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get VM List
      vmware_vm_info:
        hostname: "192.168.50.26"
        username: "root"
        password: "your_password"
        validate_certs: no
      delegate_to: localhost
      register: vm_list

    - name: Display VM List
      debug:
        var: vm_list.virtual_machines