---
- name: Check Windows service
  hosts: "{{ win_vm }}"
  gather_facts: false

  tasks:

    - name: Fetch windows service info
      ansible.windows.win_service_info:
        name: "{{ win_service_name }}"
      register: service_info

    - name: Print the service info 
      debug:
        var: service_info
