- name: 'POSTCHK_SCRIPT | Check if post check script found any difference'
  ansible.builtin.set_fact:
    post_check_script_diff: '{{ true if postcheck_script_result.stdout is search("ERROR:") else false}}'
    # There is no difference for pre - post script outputs but we provide the post script output
    post_check_script_diff_val: "{{ postcheck_script_result.stdout_lines }}"
  #when: postcheck_script_result.stdout is search("ERROR:")