---
- hosts: localhost
  
  tasks:
    - name: Include Secret Environment Items
      include_vars:
        file: secrets.yml
        name: secret

    - name: snapshots
  community.vmware.vmware_guest_snapshot:
    hostname: "{{secret.vcenter}}"
    username: "{{secret.username}}"
    password: "{{secret.password}}"
    datacenter: "DC"
    folder: "/{{ datacenter_name }}/vm/"
    name: "test"
    state: absent
    snapshot_name: Ansible-Prepatch-Snapshot
    description:
  delegate_to: localhost